# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-01 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerType', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('convNumber', models.IntegerField(default=1)),
                ('imgFile', models.FileField(upload_to='tpo/static/images/')),
                ('audioFile', models.FileField(upload_to='tpo/static/audio/')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningPartOfQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgFile', models.FileField(null=True, upload_to='tpo/static/images/')),
                ('audioFile', models.FileField(null=True, upload_to='tpo/static/audio/')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('number', models.IntegerField(default=1)),
                ('isAnswer', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1200)),
                ('orderingNumber', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('passageNumber', models.IntegerField(default=1)),
                ('questionCount', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionNumber', models.IntegerField(default=1)),
                ('text', models.CharField(max_length=1200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingPartOfQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('readingTime', models.IntegerField(default=45)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('respFile', models.FileField(upload_to='tpo/static/audio/')),
                ('tpoNo', models.IntegerField(default=1)),
                ('questionNo', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(default=1)),
                ('text', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ListeningPartOfSpeakingQuestion',
            fields=[
                ('listeningpartofquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tpo.ListeningPartOfQuestion')),
            ],
            bases=('tpo.listeningpartofquestion',),
        ),
        migrations.CreateModel(
            name='ListeningPartOfWritingQuestion',
            fields=[
                ('listeningpartofquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tpo.ListeningPartOfQuestion')),
            ],
            bases=('tpo.listeningpartofquestion',),
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tpo.Question')),
                ('questionAudioFile', models.FileField(null=True, upload_to='tpo/static/audio/')),
                ('preAudioFile', models.FileField(null=True, upload_to='tpo/static/audio/')),
                ('imgFile', models.FileField(null=True, upload_to='tpo/static/images/')),
            ],
            bases=('tpo.question',),
        ),
        migrations.CreateModel(
            name='ReadingPartOfSpeakingQuestion',
            fields=[
                ('readingpartofquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tpo.ReadingPartOfQuestion')),
                ('title', models.CharField(max_length=100)),
            ],
            bases=('tpo.readingpartofquestion',),
        ),
        migrations.CreateModel(
            name='ReadingPartOfWritingQuestion',
            fields=[
                ('readingpartofquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tpo.ReadingPartOfQuestion')),
            ],
            bases=('tpo.readingpartofquestion',),
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tpo.Question')),
                ('startHighlight', models.IntegerField(default=1, null=True)),
                ('endHighlight', models.IntegerField(default=1, null=True)),
            ],
            bases=('tpo.question',),
        ),
        migrations.CreateModel(
            name='SpeakingQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tpo.Question')),
                ('questionAudioFile', models.FileField(null=True, upload_to='tpo/static/audio/')),
                ('questionDescription', models.FileField(null=True, upload_to='tpo/static/audio/')),
                ('preparationTime', models.IntegerField(default=1)),
                ('responseTime', models.IntegerField(default=1)),
                ('tpo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.TPO')),
            ],
            bases=('tpo.question',),
        ),
        migrations.CreateModel(
            name='WritingQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tpo.Question')),
                ('responseTime', models.IntegerField(default=1)),
                ('tpo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.TPO')),
            ],
            bases=('tpo.question',),
        ),
        migrations.AddField(
            model_name='question',
            name='questionType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.QuestionType'),
        ),
        migrations.AddField(
            model_name='passage',
            name='tpo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.TPO'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='passage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.Passage'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.Question'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='tpo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.TPO'),
        ),
        migrations.AddField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.Option'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.Question'),
        ),
        migrations.AddField(
            model_name='readingquestion',
            name='paragraph',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.Paragraph'),
        ),
        migrations.AddField(
            model_name='readingpartofwritingquestion',
            name='sQuestion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.SpeakingQuestion'),
        ),
        migrations.AddField(
            model_name='readingpartofspeakingquestion',
            name='sQuestion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.SpeakingQuestion'),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='conversation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.Conversation'),
        ),
        migrations.AddField(
            model_name='listeningpartofwritingquestion',
            name='sQuestion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.WritingQuestion'),
        ),
        migrations.AddField(
            model_name='listeningpartofspeakingquestion',
            name='sQuestion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.SpeakingQuestion'),
        ),
    ]
