# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0003_passage_passagenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('convNumber', models.IntegerField(default=1)),
                ('imgFile', models.FileField(upload_to='tpo/static/images/')),
                ('audioFile', models.FileField(upload_to='tpo/static/audio/')),
                ('tpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.TPO')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('respFile', models.FileField(upload_to='tpo/static/images/')),
            ],
        ),
        migrations.AddField(
            model_name='passage',
            name='questionCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='endHighlight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='startHighlight',
            field=models.IntegerField(default=1),
        ),
    ]
