# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0005_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakingresponse',
            name='respFile',
            field=models.FileField(upload_to='tpo/static/audio/'),
        ),
    ]
