# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0006_auto_20170425_2128'),
        ('tpo', '0004_auto_20170421_2109'),
    ]

    operations = [
    ]
