# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0007_merge_20170427_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tpo.Question')),
                ('questionAudioFile', models.FileField(null=True, upload_to='tpo/static/audio/')),
                ('preAudioFile', models.FileField(null=True, upload_to='tpo/static/audio/')),
                ('imgFile', models.FileField(null=True, upload_to='tpo/static/images/')),
            ],
            bases=('tpo.question',),
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tpo.Question')),
                ('startHighlight', models.IntegerField(default=1, null=True)),
                ('endHighlight', models.IntegerField(default=1, null=True)),
            ],
            bases=('tpo.question',),
        ),
        migrations.RemoveField(
            model_name='question',
            name='endHighlight',
        ),
        migrations.RemoveField(
            model_name='question',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='question',
            name='startHighlight',
        ),
        migrations.AlterField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.Option'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.Question'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='tpo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.TPO'),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.Question'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='passage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.Passage'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='tpo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.TPO'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.QuestionType'),
        ),
        migrations.AddField(
            model_name='readingquestion',
            name='paragraph',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.Paragraph'),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='conversation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.Conversation'),
        ),
    ]
