# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0008_auto_20170427_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='speakingQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tpo.Question')),
                ('questionAudioFile', models.FileField(null=True, upload_to='tpo/static/audio/')),
                ('questionDescription', models.FileField(null=True, upload_to='tpo/static/audio/')),
                ('preparationTime', models.IntegerField(default=1)),
            ],
            bases=('tpo.question',),
        ),
    ]
