# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0009_speakingquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('respFile', models.FileField(upload_to='tpo/static/images/')),
            ],
        ),
        migrations.AlterField(
            model_name='speakingresponse',
            name='respFile',
            field=models.FileField(upload_to='tpo/static/audio/'),
        ),
    ]
