# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0010_auto_20170428_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingquestion',
            name='tpo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.TPO'),
        ),
    ]
