# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0011_speakingquestion_tpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakingquestion',
            name='preparationTime',
            field=models.TimeField(blank=True),
        ),
    ]
