# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0012_auto_20170428_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakingquestion',
            name='preparationTime',
            field=models.IntegerField(default=1),
        ),
    ]
