# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0013_auto_20170428_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingquestion',
            name='responseTime',
            field=models.IntegerField(default=1),
        ),
    ]
