# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0015_auto_20170428_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningPartOfSpeakingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgFile', models.FileField(null=True, upload_to='tpo/static/images/')),
                ('AudioFile', models.FileField(null=True, upload_to='tpo/static/audio/')),
                ('sQuestion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.SpeakingQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingPartOfSpeakingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('readingTime', models.IntegerField(default=45)),
                ('title', models.CharField(max_length=100)),
                ('sQuestion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpo.SpeakingQuestion')),
            ],
        ),
    ]
