# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-27 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebookShop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='details',
            field=models.TextField(default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='fav',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='onSale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='bigPhoto',
            field=models.ImageField(null=True, upload_to=b'img'),
        ),
        migrations.AddField(
            model_name='category',
            name='smallPhoto',
            field=models.ImageField(null=True, upload_to=b'img'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ebookShop.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ebookShop.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='coverPhoto',
            field=models.ImageField(upload_to=b'img'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ebookShop.Publication'),
        ),
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ebookShop.Format'),
        ),
    ]
